modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/MoSadie/EffectMC/issues"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/MoSadie/EffectMC/main/MinecraftMod/forge/update.json"
displayURL="https://github.com/MoSadie/EffectMC"
authors="${mod_authors}"
displayTest="IGNORE_ALL_VERSION"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}
    ordering="NONE"
    side="BOTH"
