name: Build 1.8.9

on:
    push:
        paths:
            - 'MinecraftMod/forge/1.8.9/**'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
    
          # Setup JDK
          - name: Set up JDK 8
            uses: actions/setup-java@v4
            with:
              distribution: adopt
              java-version: 8
    
          - name: Set up Gradle
            uses: gradle/actions/setup-gradle@v3
    
          # Build Core
          - name: Build/Install Core
            working-directory: ./MinecraftMod/core
            run: './gradlew publishToMavenLocal'

            # Build Minecraft Mod
          - name: Build Mod
            working-directory: ./MinecraftMod/forge/1.8.9
            run: './gradlew build --no-daemon'

            # Upload Artifact
          - name: Upload Artifact
            uses: actions/upload-artifact@v4
            with:
                name: forge 1.8.9
                path: ./MinecraftMod/forge/1.8.9/build/libs/*.jar
