name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  buildJava8:
    name: Build ${{ matrix.mod-loader }} ${{ matrix.mc-version }}
    runs-on: ubuntu-latest
    
    # Matrix of jobs to run
    strategy:
      matrix:
        mod-loader: ['forge', 'fabric']
        mc-version: ['1.16.4']
        #exclude:
        #  - mod-loader: 'forge'
        #    mc-version: '1.17'
        
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Setup JDK
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          
      # Build Core
      - name: Build/Install Core
        working-directory: ./MinecraftMod/core
        run: './gradlew publishToMavenLocal'
          
      # Build Minecraft Mod
      - name: Build Mod
        working-directory: ./MinecraftMod/${{ matrix.mod-loader }}/${{ matrix.mc-version }}
        run: './gradlew build --no-daemon'

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.mod-loader }} ${{ matrix.mc-version }}
          path: ./MinecraftMod/${{ matrix.mod-loader }}/${{ matrix.mc-version }}/build/libs/*.jar

  buildJava16:
    name: Build ${{ matrix.mod-loader }} ${{ matrix.mc-version }}
    runs-on: ubuntu-latest
    
    # Matrix of jobs to run
    strategy:
      matrix:
        mod-loader: ['fabric']
        mc-version: ['1.17']
        #exclude:
        #  - mod-loader: 'forge'
        #    mc-version: '1.17'
        
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Setup JDK
      - name: Set up JDK 1.16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          
      # Build Core
      - name: Build/Install Core
        working-directory: ./MinecraftMod/core
        run: './gradlew publishToMavenLocal'

      # Setup JDK
      - name: Set up JDK 1.16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
          
      # Build Minecraft Mod
      - name: Build Mod
        working-directory: ./MinecraftMod/${{ matrix.mod-loader }}/${{ matrix.mc-version }}
        run: './gradlew build --no-daemon'

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.mod-loader }} ${{ matrix.mc-version }}
          path: ./MinecraftMod/${{ matrix.mod-loader }}/${{ matrix.mc-version }}/build/libs/*.jar

  buildPlugin:
    name: Build Stream Deck Plugin
    runs-on: windows-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Download DistributionTool from Elgato
      - name: Download DistributionTool
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://developer.elgato.com/documentation/stream-deck/distributiontool/DistributionToolWindows.zip'
        
      # Unzip DistributionTool
      - name: Unzip DistributionTool
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: './DistributionToolWindows.zip'
          pathTarget: './StreamDeckPlugin'
          
      # Run DistributionTool
      - name: Run DistributionTool
        working-directory: './StreamDeckPlugin'
        run: './DistributionTool.exe -b -i io.github.mosadie.effectmc.sdPlugin -o .'
        
      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Stream Deck Plugin
          path: ./StreamDeckPlugin/*.streamDeckPlugin
